name: Release-NPM

on: [release]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Release to npm
        run: |
          npm ci
          npm install
          npm set //registry.npmjs.org/:_authToken $NPM_AUTH_TOKEN
          npm publish
        env:
          CI: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
